name: Terraform CI

on:
  push:
    branches:
      - feature/pipeline

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/Pre_Prod

    steps:

      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: be6e1338-5287-4e4a-a50d-a453d84969d8
          tenant-id: e8d592ab-f2df-4543-882e-e0e0db835e04
          subscription-id: 370b2d3a-e01b-4f6f-8d7c-760f75894068     

      # Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Generate Terraform plan
      - name: Terraform Plan
        run: terraform plan
