name: Terraform CD - Pre-Prod

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:

  # ===================================================
  # PLAN
  # ===================================================
  terraform-plan:
    name: Terraform Plan - Pre-Prod
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/Pre_Prod

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: be6e1338-5287-4e4a-a50d-a453d84969d8
          tenant-id: e8d592ab-f2df-4543-882e-e0e0db835e04
          subscription-id: 370b2d3a-e01b-4f6f-8d7c-760f75894068

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_ssh_public_key: ${{ secrets.AZURE_VM_SSH_PUBLIC_KEY }}
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Environment/Pre_Prod/tfplan


  # ===================================================
  # APPLY
  # ===================================================
  terraform-apply:
    name: Terraform Apply - Pre-Prod
    runs-on: ubuntu-latest

    needs: terraform-plan

    environment:
      name: Pre-Prod

    defaults:
      run:
        working-directory: Environment/Pre_Prod

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: be6e1338-5287-4e4a-a50d-a453d84969d8
          tenant-id: e8d592ab-f2df-4543-882e-e0e0db835e04
          subscription-id: 370b2d3a-e01b-4f6f-8d7c-760f75894068

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: Environment/Pre_Prod

      - name: Terraform Apply
        env:
          TF_VAR_ssh_public_key: ${{ secrets.AZURE_VM_SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve tfplan