name: Terraform CI

on:
  push:
    branches:
      - feature/pipeline

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/Preprod

    steps:

      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Generate Terraform plan
      - name: Terraform Plan
        run: terraform plan